[package]
name = "gfx_text"
version = "0.9.0"
authors = ["Kagami Hiiragi <kagami@genshiken.org>"]
description = "Draw text for gfx using freetype."
keywords = ["gfx", "graphics", "text", "freetype", "font"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/PistonDevelopers/gfx_text"
repository = "https://github.com/PistonDevelopers/gfx_text.git"
documentation = "http://docs.piston.rs/gfx_text/gfx_text/"

[dependencies]
gfx = "0.10.2"
freetype-rs = "0.7.0"

[features]
default = ["include-font"]
include-font = []

### For examples

[dev-dependencies]
gfx_window_glutin = "0.10.0"
glutin = "0.4.8"
#log = "*"
#env_logger = "*"
