[package]
name = "gfx_text"
version = "0.0.0"
authors = ["Kagami Hiiragi <kagami@genshiken.org>"]

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs"

[dependencies.gfx_macros]
git = "https://github.com/gfx-rs/gfx_macros"

[dependencies.freetype-rs]
git = "https://github.com/PistonDevelopers/freetype-rs"

### For examples

[dev-dependencies.gfx_window_glutin]
git = "https://github.com/gfx-rs/gfx_window_glutin"

[dev-dependencies.glutin]
git = "https://github.com/tomaka/glutin"
