[package]
name = "gfx_text"
version = "0.0.0"
authors = ["Kagami Hiiragi <kagami@genshiken.org>"]

[dependencies]
log = "*"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs"

[dependencies.freetype-rs]
git = "https://github.com/PistonDevelopers/freetype-rs"

### For examples

[dev-dependencies]
env_logger = "*"

[dev-dependencies.gfx_window_glutin]
git = "https://github.com/gfx-rs/gfx_window_glutin"

[dev-dependencies.glutin]
git = "https://github.com/tomaka/glutin"
